version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - .:/app
      - ./frankenphp.yaml:/etc/frankenphp/frankenphp.yaml
      - ./.docker/certs/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./.docker/certs/localhost.key:/etc/ssl/private/localhost.key
    environment:
      APP_ENV: dev
      COMPOSER_ALLOW_SUPERUSER: 1
      DATABASE_URL: "mysql://symfony:password@database:3306/footbrainpro?serverVersion=8.0"
    depends_on:
      - database

  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: footbrainpro
      MYSQL_USER: symfony
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3308:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"  # Accès via http://localhost:8081
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - database

volumes:
  db-data:




#services:
####> doctrine/doctrine-bundle ###
#  database:
#    image: postgres:${POSTGRES_VERSION:-16}-alpine
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB:-app}
#      # You should definitely change the password in production
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
#      POSTGRES_USER: ${POSTGRES_USER:-app}
#    healthcheck:
#      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
#      timeout: 5s
#      retries: 5
#      start_period: 60s
#    volumes:
#      - database_data:/var/lib/postgresql/data:rw
#      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
#      # - ./docker/db/data:/var/lib/postgresql/data:rw
####< doctrine/doctrine-bundle ###
#
#volumes:
####> doctrine/doctrine-bundle ###
#  database_data:
####< doctrine/doctrine-bundle ###
