version: '3.8'

services:
  app:
    build:
      context: .
    environment:
      APP_ENV: dev
      COMPOSER_ALLOW_SUPERUSER: 1
      DATABASE_URL: "mysql://symfony:password@database:3306/footbrainpro?serverVersion=8.0"
    depends_on:
      - database

  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: footbrainpro
      MYSQL_USER: symfony
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
