FROM php:8.2-apache
RUN a2enmod rewrite
COPY . /var/www/html
ADD ./000-default-prod.conf /etc/apache2/sites-available

RUN apt-get update
RUN docker-php-ext-install pdo pdo_mysql
RUN apt-get install -y zlib1g-dev libicu-dev g++
RUN docker-php-ext-configure intl
RUN docker-php-ext-install intl
RUN curl -sL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs \
    && apt-get clean
