FROM php:8.2-apache
RUN a2enmod rewrite
COPY . /var/www/html
ADD ./000-default-dev.conf /etc/apache2/sites-available

RUN apt-get update
RUN docker-php-ext-install pdo pdo_mysql
RUN apt-get install -y zlib1g-dev libicu-dev g++
RUN docker-php-ext-configure intl
RUN docker-php-ext-install intl
RUN curl -sL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs \
    && apt-get clean \
RUN apt-get install -y git unzip && \
    curl -sS https://getcomposer.org/installer | php && \
    php composer.phar install --no-scripts --no-interaction && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
