### ✅ ci_dev.yml : CI sur PR vers `dev`
name: Dev PR CI
on:
  pull_request:
    branches: [ dev ]
    paths-ignore:
      - 'config/packages/reset_password.yaml'
jobs:
  ci:
    runs-on: ubuntu-latest
    continue-on-error: false # or true
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # https://github.com/shivammathur/setup-php (community)
      - name: Setup PHP, extensions and composer with shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, iconv, json, mbstring, pdo
          php-version: 8.2

      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            vendor
          key: ${{ runner.os }}-${{ hashFiles('composer.lock') }}

      - name: "Composer install"
        run: composer install --no-interaction --no-progress

      # Install Symfony CLI
      - name: Symfony CLI
        run: |
          curl -sS https://get.symfony.com/cli/installer | bash
          mv /home/runner/.symfony5/bin/symfony /usr/local/bin/symfony

      # Check vulnerabilities
      - name: Symfony Check Vulnerabilities
        run: symfony check:security

      # PHP STAN
      - name: PHP Stan
        run: |
          ./vendor/bin/simple-phpunit install
          composer require phpstan/phpstan
          composer require phpstan/extension-installer
          composer require phpstan/phpstan-symfony
          ./vendor/bin/phpstan analyse src --memory-limit 1G

      # PHPUnit tests
      - name: PHPUnit
        run: ./vendor/bin/phpunit --configuration phpunit.xml.dist

      # Check Twig Core syntax
      - name: Twig Core Template Lint
        run: ./bin/console lint:twig core/templates --env=dev

      # Check Twig syntax
      - name: Twig Template Lint
        run: ./bin/console lint:twig templates --env=dev

      # Check YAML syntax
      - name: Lint YAML files
        run: ./bin/console lint:yaml config --parse-tags

      # Check service parameter
      - name: Lint Parameters and Services
        run: ./bin/console lint:container --no-debug

      # Check doctrine entities schema
      - name: Lint Doctrine entities
        run: ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction
