### ✅ deploy_on_main_push.yml : build & push image Docker en production (tag = `latest`)
name: Deploy to Prod on merge to main
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Prod Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/footbrainpro:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/footbrainpro:latest

      - name: 🚀 Deploy to PROD via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/footbrainpro:latest
            sudo docker-compose up -d --remove-orphans
            sleep 10
            CONTAINER_FOOTBRAINPRO=$(sudo docker ps --filter ancestor=${{ secrets.DOCKER_USERNAME }}/footbrainpro_dev:latest --format "{{.Names}}" | head -n 1)
            sudo docker exec $CONTAINER_FOOTBRAINPRO php bin/console cache:clear
            sudo docker exec $CONTAINER_FOOTBRAINPRO npm install
            sudo docker exec $CONTAINER_FOOTBRAINPRO php bin/console doctrine:database:create --if-not-exists
            sudo docker exec $CONTAINER_FOOTBRAINPRO php bin/console doctrine:migrations:migrate --no-interaction --env=prod
            sudo docker exec $CONTAINER_FOOTBRAINPRO rm -rf public/assets
            sudo docker exec $CONTAINER_FOOTBRAINPRO php bin/console importmap:install
            sudo docker exec $CONTAINER_FOOTBRAINPRO sass assets/styles/app.scss:assets/styles/app.css
            sudo docker exec $CONTAINER_FOOTBRAINPRO php bin/console asset-map:compile
            sudo docker exec $CONTAINER_FOOTBRAINPRO php bin/console cache:clear --env=prod
            sudo docker exec $CONTAINER_FOOTBRAINPRO php bin/console cache:warmup --env=prod
            sudo docker exec $CONTAINER_FOOTBRAINPRO php bin/console doctrine:cache:clear-metadata --env=prod
