### ✅ deploy_on_main_push.yml : build & push image Docker en production (tag = `latest`)
name: 🚀 Deploy to Prod (footbrainpro.com) on merge to main

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🧱 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔐 Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 🛠️ Build and Push Prod Image
        run: |
          # Remplace dynamiquement le tag dans le fichier compose
          sed "s|IMAGE_TAG|${{ github.sha }}|g" compose.prod.yaml > compose.prod.built.yaml

          # Build & push via Docker Compose
          docker compose -f compose.prod.built.yaml build
          docker tag footbrainpro_app:latest ${{ secrets.DOCKER_USERNAME }}/footbrainpro_prod:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/footbrainpro_prod:${{ github.sha }}

      - name: 🚀 Deploy to PROD via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull de l’image fraîchement buildée
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/footbrainpro_prod:${{ github.sha }}
            # Stoppe et supprime les conteneurs utilisant l'image (optionnel si `--remove-orphans` gère tout)
            sudo docker-compose down
            # Supprime l'image only si elle existe
            sudo docker rmi footbrainpro_prod:latest || true
            # Retag
            sudo docker tag ${{ secrets.DOCKER_USERNAME }}/footbrainpro_prod:${{ github.sha }} footbrainpro_prod:latest
            # Redémarre les services
            sudo docker-compose up -d --remove-orphans
            
            # Arrêt de 10 secondes
            sleep 10

            # Récupère le nom du conteneur
            CONTAINER_FOOTBRAINPRO=$(sudo docker ps --filter ancestor=footbrainpro_prod:latest --format "{{.Names}}" | head -n 1)

            # Nettoyage du cache (dev)
            sudo docker exec $CONTAINER_FOOTBRAINPRO php bin/console cache:clear

            # Installation des dépendances front
            sudo docker exec $CONTAINER_FOOTBRAINPRO npm install

            # Création de la BDD si non existante
            sudo docker exec $CONTAINER_FOOTBRAINPRO php bin/console doctrine:database:create --if-not-exists

            # Migration de la base de données (prod)
            sudo docker exec $CONTAINER_FOOTBRAINPRO php bin/console doctrine:migrations:migrate --no-interaction --env=prod

            # Suppression des assets obsolètes
            sudo docker exec $CONTAINER_FOOTBRAINPRO rm -rf public/assets

            # Installation d'importmap
            sudo docker exec $CONTAINER_FOOTBRAINPRO php bin/console importmap:install

            # Compilation des styles SCSS
            sudo docker exec $CONTAINER_FOOTBRAINPRO sass assets/styles/app.scss:assets/styles/app.css

            # Compilation de asset-map
            sudo docker exec $CONTAINER_FOOTBRAINPRO php bin/console asset-map:compile

            # Nettoyage du cache (prod)
            sudo docker exec $CONTAINER_FOOTBRAINPRO php bin/console cache:clear --env=prod

            # Préchauffage du cache (prod)
            sudo docker exec $CONTAINER_FOOTBRAINPRO php bin/console cache:warmup --env=prod

            # Nettoyage du cache Doctrine
            sudo docker exec $CONTAINER_FOOTBRAINPRO php bin/console doctrine:cache:clear-metadata --env=prod
