### ✅ deploy_on_dev_push.yml : build & push image Docker en dev (tag = commit SHA)
name: Deploy to Dev on merge to dev
on:
  push:
    branches: [ dev ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Dev Image
        run: |
          # Remplace dynamiquement le tag dans le fichier compose
          sed "s|IMAGE_TAG|${{ github.sha }}|g" compose.dev.yaml > compose.dev.built.yaml

          # Build & push via Docker Compose
          docker compose -f compose.dev.built.yaml build
          docker tag footbrainpro_app:latest ${{ secrets.DOCKER_USERNAME }}/footbrainpro:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/footbrainpro:${{ github.sha }}
          docker tag footbrainpro_app:latest ${{ secrets.DOCKER_USERNAME }}/footbrainpro_dev:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/footbrainpro_dev:latest

      - name: 🚀 Deploy to DEV via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/footbrainpro_dev:latest
            sudo docker-compose up -d --remove-orphans
            sleep 10
            CONTAINER_NAME=$(docker ps --filter ancestor=khaleddwm/footbrainpro_dev:latest --format "{{.Names}}" | head -n 1)
            sudo docker exec $CONTAINER_NAME php bin/console cache:clear
            sudo docker exec $CONTAINER_NAME npm install
            sudo docker exec $CONTAINER_NAME php bin/console doctrine:database:create --if-not-exists
            sudo docker exec $CONTAINER_NAME php bin/console doctrine:migrations:migrate --no-interaction
            sudo docker exec $CONTAINER_NAME php bin/console importmap:install
