### ✅ deploy_on_dev_push.yml : build & push image Docker en dev (tag = commit SHA)
name: 🧪 Deploy to Dev (dev.footbrainpro.com) on merge to dev

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🧱 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔐 Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 🛠️ Build and Push Dev Image
        run: |
          # Remplace dynamiquement le tag dans le fichier compose
          sed "s|IMAGE_TAG|${{ github.sha }}|g" compose.dev.yaml > compose.dev.built.yaml

          # Build & push via Docker Compose
          docker compose -f compose.dev.built.yaml build
          docker tag footbrainpro_app:latest ${{ secrets.DOCKER_USERNAME }}/footbrainpro_dev:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/footbrainpro_dev:${{ github.sha }}

      - name: 🚀 Deploy to DEV via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull de l’image fraîchement buildée
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/footbrainpro_dev:${{ github.sha }}
            # Stoppe et supprime les conteneurs utilisant l'image (optionnel si `--remove-orphans` gère tout)
            sudo docker-compose down
            # Supprime l'image only si elle existe
            sudo docker rmi footbrainpro_dev:latest || true
            # Retag
            sudo docker tag ${{ secrets.DOCKER_USERNAME }}/footbrainpro_dev:${{ github.sha }} footbrainpro_dev:latest
            # Redémarre les services
            sudo docker-compose up -d --remove-orphans
            
            # Arrêt de 10 secondes
            sleep 10
            
            # Récupère le nom du conteneur
            CONTAINER_FOOTBRAINPRO_DEV=$(sudo docker ps --filter ancestor=footbrainpro_dev:latest --format "{{.Names}}" | head -n 1)

            # Nettoyage du cache
            sudo docker exec $CONTAINER_FOOTBRAINPRO_DEV php bin/console cache:clear

            # Installation des dépendances front
            sudo docker exec $CONTAINER_FOOTBRAINPRO_DEV npm install

            # Création de la base de données (si non existante)
            sudo docker exec $CONTAINER_FOOTBRAINPRO_DEV php bin/console doctrine:database:create --if-not-exists

            # Migration de la base de données
            sudo docker exec $CONTAINER_FOOTBRAINPRO_DEV php bin/console doctrine:migrations:migrate --no-interaction

            # Suppression des assets obsolètes
            sudo docker exec $CONTAINER_FOOTBRAINPRO_DEV rm -rf public/assets

            # Installation d'importmap
            sudo docker exec $CONTAINER_FOOTBRAINPRO_DEV php bin/console importmap:install

            # Compilation des styles SCSS → CSS
            sudo docker exec $CONTAINER_FOOTBRAINPRO_DEV sass assets/styles/app.scss:assets/styles/app.css

            # Compilation de asset-map
            sudo docker exec $CONTAINER_FOOTBRAINPRO_DEV php bin/console asset-map:compile
            
            # Nettoyage du cache
            sudo docker exec $CONTAINER_FOOTBRAINPRO_DEV php bin/console cache:clear
