### ✅ deploy_on_main_push.yml : build & push image Docker en production (tag = `latest`)
name: Deploy to Prod on merge to main

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Docker Login
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Prod Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/footbrainpro:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/footbrainpro:latest

      - name: 🚀 Deploy to PROD via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
#            cd /var/www/ton-projet
            docker compose pull
            docker compose up -d
