### ✅ deploy_on_dev_push.yml : build & push image Docker en dev (tag = commit SHA)
name: Deploy to Dev on merge to dev
on:
  push:
    branches: [ dev ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Dev Image
        run: |
          # Remplace dynamiquement le tag dans le fichier compose
          sed "s|IMAGE_TAG|${{ github.sha }}|g" compose.dev.yaml > compose.dev.built.yaml

          # Build & push via Docker Compose
          docker compose -f compose.dev.built.yaml build
          docker tag footbrainpro_app:latest ${{ secrets.DOCKER_USERNAME }}/footbrainpro:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/footbrainpro:${{ github.sha }}

      - name: 🚀 Deploy to DEV via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sed -i "s/IMAGE_TAG/${{ github.sha }}/g" docker-compose.yml
            docker-compose pull
            docker-compose up -d
